spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 5
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        password: root
        url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
        username: root
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
